name: Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        run: |
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "APP_URL=${{ secrets.APP_URL }}" >> .env
          echo "CHANNEL_ACCESS_TOKEN=${{ secrets.CHANNEL_ACCESS_TOKEN }}" >> .env
          echo "CHANNEL_SECRET=${{ secrets.CHANNEL_SECRET }}" >> .env
          echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "SERVER_HOST=${{ secrets.SERVER_HOST }}" >> .env
          echo "SERVER_USERNAME=${{ secrets.SERVER_USERNAME }}" >> .env
          echo "SERVER_PASSWORD=${{ secrets.SERVER_PASSWORD }}" >> .env
          echo "SERVER_PATH=${{ secrets.SERVER_PATH }}" >> .env
      - name: Send .env file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: ".env"
          target: "${{ secrets.SERVER_PATH }}"
      - name: SSH
        uses: "appleboy/ssh-action@master"
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ secrets.SERVER_PATH }}
            git reset --hard
            git pull --rebase
            composer2 install --no-dev --optimize-autoloader
